### ISSUE TITLE
Several outputs per cell

### ISSUE THREAD

**Issue by pedritomelenas** [gap-packages/JupyterKernel#19]
I do not think that having several ouputs for a single cell is bad (though having as ouput the last output in that cell could be also ok). The problem arises in examples like the following.
```
a:=[1,"a"];
b:=a;
b[2]:=3;
a;
```
ouputs `[1,3]`, `[1,3]`, `3`, and `[1,3]`. The first should probably be `[1,"a"]`.

Thanks,
Pedro

**Comment by markuspf** [comment]
The problem here is that all input is evaluated and only then are results printed, so the list pointed at by `a`, at the point of printing, is `[1,3]`.

I submitted a change GAP to copy each result, which is potentially expensive, but before I (or someone else) have sorted out parsing from a stream in bits this is the best I can do.

**Comment by markuspf** [comment]
https://github.com/gap-system/gap/pull/1799
