### ISSUE TITLE
time variable does not work

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/JupyterKernel#39]
It shows e.g. `11` ms if a command ran for a few seconds.

**Comment by markuspf** [comment]
I see the following options to address this problem:

 1) Remove access to `time` (because I am not sure it serves a useful purpose, anyway, and it certainly becomes even less useful if you run things in a container)
 2) make time reflect the time it took to execute the cell
 3) have timing for every statement in the cell

for options 2 or three I am happy to explain how to approach this for a pull request to appear.

**Comment by alex-konovalov** [comment]
+1 for option 2

**Comment by alex-konovalov** [comment]
Came across this while working on a demo I intend to give this week. @markuspf do you have any tips for option 2 then?

**Comment by markuspf** [comment]
This is resolved with 85e9fc2f73aa1476c0890191f2aa4a8942c70dfc

**Comment by alex-konovalov** [comment]
Thanks - close it then?
