### ISSUE TITLE
Version 1.0 incompatible with GAP master and stable-4.10 branches.

### ISSUE THREAD

**Issue by markuspf** [gap-packages/JupyterKernel#88]
https://mybinder.org/v2/gh/gap-packages/OrbitalGraphs/master

**Comment by alex-konovalov** [comment]
The reason is that JupyterKernel 1.0 works in GAP 4.10.0 (in `gap-docker` container), but `OrbitalGraphs` is using `gap-docker-master`, where version 1.0 is included but it does not work. To get it to work both in `gap-docker-master` and `gap-docker-stable-4.10` containers, one should get JupyterKernel 1.1 with 587a1230e330ec5756ca652134c98a05c3465806 included. However, JupyterKernel 1.1 has been picked up for the redistribution, but did not pass internal testing in Jenkins, as reported in #89, so it's not approved.
